"""MCP tool and prompt description strings.

These are protocol-contract texts — what MCP clients see as tool/prompt
documentation.  Keeping them here lets server.py focus on wiring.
"""

MCP_SERVER_INSTRUCTIONS = (
    "Use this MCP server for local constraint programming and optimization: "
    "MiniZinc and CP-SAT models for scheduling, rostering, knapsack, "
    "allocation, assignment, routing, bin-packing, SAT/UNSAT analysis, model "
    "validation, and solver statistics. For natural-language problems, prefer "
    "the solve_constraint_problem prompt when the client supports MCP prompts; "
    "otherwise draft MiniZinc in the client LLM, check it with "
    "check_minizinc_model, then solve with solve_minizinc_model. To discover "
    "which parameters a model needs as data before building a `.dzn` (and its "
    "output variables and solve method), inspect its interface with "
    "inspect_minizinc_model without solving. When the "
    "model (and any data) already exist as local files, pass their paths to "
    "check_minizinc_files / solve_minizinc_files instead of reading the files "
    "into the string tools — the path-based tools run from the model's own "
    "directory, so a relative `include` resolves. To validate produced solutions, "
    "pass an optional solution checker to the solve tools (`checker` for inline "
    "source, `checker_path` for file solves). After a successful checked/solved "
    "inline model, the client can persist it with save_verified_minizinc_model "
    "and an explicit absolute `target_dir` — the server re-verifies through the "
    "managed runtime before writing and never opens a file dialog. "
    "Either way, lead with the "
    "result: a plain-language status, the stdout solution stated in the "
    "terms of the user's problem (not the raw JSON SolveResult), a compact "
    "item table when the problem supplies item-like data, and the complete "
    "model-visible `Statistics:` section when present. Do not condense it to "
    "selected fields. Use `num_solutions` only with `org.gecode.gecode` or "
    "`org.chuffed.chuffed`, not the default `cp-sat`; for multiple optimal "
    "solutions, solve the optimization first, then re-solve as satisfaction "
    "with the objective fixed to the proven optimum. The check/inspect/solve/"
    "unsat-core tools emit optional status feedback while MiniZinc runs: MCP "
    "progress notifications when the request carries `_meta.progressToken`, "
    "plus info-level MCP log notifications always — stage markers, not a "
    "solver completion percentage, so never render them as a percent bar. All "
    "execution must use the managed local MiniZinc "
    "runtime; do not use remote solvers or a bare PATH minizinc."
)

CHECK_RUNTIME_DESCRIPTION = "Report whether the managed MiniZinc runtime is installed."

LIST_AVAILABLE_SOLVERS_DESCRIPTION = (
    "List solvers available in the managed MiniZinc runtime. Returns a "
    "SolverList of SolverInfo entries — each with `id`, `name`, `version`, "
    "`tags`, and a `capabilities` object of deterministic facts read from the "
    "managed runtime's own `--solvers-json` config, for client-side solver "
    "routing. `capabilities.supports_all_solutions` (`-a`), `supports_free_search` "
    "(`-f`), `supports_parallel` (`-p`), and `supports_random_seed` (`-r`) report "
    "membership in the solver's declared `stdFlags`. `supports_num_solutions` "
    "(`-n`) is NOT a raw stdFlags read: it is the conservative canonical gate "
    "matching the `num_solutions` solve control — True only for "
    "`org.gecode.gecode` and `org.chuffed.chuffed`, not the default `cp-sat`. "
    "Capabilities are advisory facts, not enforcement: the server still does not "
    "reject `-a/-f/-p/-r` at solve time. The raw advisory `std_flags` list reports "
    "the standard flags the solver configuration declares; it is NOT a passthrough "
    "surface — a client cannot send those flags back into `solve_minizinc_model` / "
    "`solve_minizinc_files`. Two cases to keep distinct: (a) `std_flags` may list "
    "standard flags the server exposes no named control for at all (e.g. `-i`, "
    "`-s`, `-t`, `-v`) — purely informational; and (b) the allowlist divergence — "
    "`org.gecode.gist` lists `-n` (which does map to the named `num_solutions` "
    "control) yet `supports_num_solutions` is False, because the conservative gate "
    "excludes gist. The model-visible text content presents a complete "
    "`id`/`name`/`version` inventory table of every solver with a final-answer "
    "requirement to copy the table without omitting rows, converting it to "
    "bullets/prose, summarizing, or grouping entries, followed by a user-visible "
    "note that detailed solver capabilities can be requested. "
    "The structured `SolverList` also carries that top-level `capability_note`. "
    "The full `capabilities` metadata (the `supports_*` booleans and `std_flags`) "
    "lives in the structured result and is not printed by default — request it "
    "explicitly to surface it."
)

SOLVE_MINIZINC_MODEL_DESCRIPTION = (
    "Solve a complete MiniZinc model through the managed local runtime. "
    "`model` must be full source: declarations, constraints, exactly one "
    "`solve` statement, and an `output` block. Optional `data` is `.dzn` "
    "text, run as a data file beside the model (omit it when the model "
    "needs none). Returns a SolveResult: `status`, `solver`, `return_code` "
    "(null on a subprocess timeout), `timed_out`, `elapsed_ms`, `stdout` "
    "(the human-readable solution text, reconstructed from the solve "
    "stream's output sections), `stderr` (the run's diagnostic channel — "
    "model/solver errors and warnings, so you can revise and retry), a "
    "structured `solution` (the best/last solution as a variable -> value "
    "map, model variables only), `solutions` (every solution in order; its "
    "last entry is `solution`), `objective` (the best objective value, null "
    "for a pure-satisfaction problem), and a best-effort `statistics` map "
    "(may be empty; keys are solver-defined), plus `checker` (null unless an "
    "optional solution checker was supplied). The structured values are "
    "emitted by the runtime's machine-readable solve stream, not scraped "
    "from text. The model-visible text content includes a `Statistics:` "
    "section whenever that map is non-empty, with an explicit final-answer "
    "requirement not to omit it; copy that entire section into the "
    "user-facing answer rather than summarizing selected fields. Optional "
    "solver/search controls (all default to current behavior, solve-only): "
    "`free_search` (bool -> `-f`: let the solver use its own search instead "
    "of the model's search annotations — solver-dependent, not 'no search'); "
    "`parallel` (int >= 1 -> `-p`: parallel search threads); `random_seed` "
    "(int -> `-r`); `all_solutions` (bool -> `-a`: enumerate all solutions, "
    "or the optimization improving-sequence, into `solutions`); "
    "`num_solutions` (int >= 1 -> `-n`: cap the number of solutions for a "
    "SATISFACTION problem; SOLVER-GATED — only `org.gecode.gecode` or "
    "`org.chuffed.chuffed`, NOT the default `cp-sat` (any other solver returns "
    "an actionable error); not meaningful for optimization — use "
    "`all_solutions` there). "
    "Optional `checker` is inline MiniZinc checker source written beside the "
    "inline model and passed via `--solution-checker`; it may include the "
    "co-located `model.mzn` but cannot resolve arbitrary project-relative local "
    "includes — use `solve_minizinc_files` with `checker_path` for multi-file "
    "checker projects. When supplied, `checker` in the SolveResult is a nested "
    "CheckerReport with `status` (`completed`, `violation`, `no_solution`, "
    "`error`, or `timeout`), `checks` (one verdict per produced solution, "
    "index-aligned with `solutions`), and `transcript` (the AUTHORITATIVE raw "
    "`--json-stream` transcript containing solve + checker objects). IMPORTANT: "
    "author `CORRECT`/`INCORRECT` text is surfaced verbatim in `checks[].output` "
    "and is NOT interpreted by the server — only a nested UNSATISFIABLE sets "
    "`violation`. The checker validates each solution; it never proves "
    "optimality — `status` remains the proof of completeness/optimality. "
    "`structuredContent` carries the complete SolveResult."
)

CHECK_MINIZINC_MODEL_DESCRIPTION = (
    "Compile-check a complete MiniZinc model through the managed local "
    "runtime WITHOUT solving it — flattening it for the chosen solver to "
    "catch syntax, type, missing-include, invalid-domain, and "
    "unsupported-construct errors so you can repair it before calling "
    "`solve_minizinc_model`. Optional `data` is `.dzn` text; a "
    "parameterized model needs the same `data` you will pass to the solve "
    "in order to flatten (omit it when the model needs none). Returns a "
    "CheckResult: `status` (`ok`/`error`/`timeout`), `solver`, raw "
    "`stdout`/`stderr`, `elapsed_ms`. `ok` means it compiles, not that it "
    "is satisfiable."
)

INSPECT_MINIZINC_MODEL_DESCRIPTION = (
    "Inspect a MiniZinc model's INTERFACE through the managed local runtime "
    "WITHOUT solving it — report which parameters it needs as data, which "
    "variables it outputs, their types (array `dim`, set-ness), and the solve "
    "`method` (`sat`/`min`/`max`), so you can build correct `.dzn` data before "
    "spending a solve. Optional `data` is `.dzn` text run beside the model "
    "(omit it when the model needs none). Returns a ModelInspectionResult: "
    "`status` (`ok`/`error`/`timeout`), `solver`, raw `stdout`/`stderr`, "
    "`elapsed_ms`, and — only when `ok` — a structured `interface` with "
    "`method`, `required_parameters`, `output_variables`, `has_output_item`, "
    "`globals`, `included_files`. `required_parameters` is the set of "
    "parameters STILL needing a value given any `data` you passed: with no "
    "data it is the model's full required set; supplying the matching data "
    "shrinks it, and an empty `required_parameters` means the data is "
    'complete. IMPORTANT: `status="ok"` means only that the interface was '
    "extracted — it is NOT a data-completeness signal; only "
    "`required_parameters == {}` is. `output_variables` is advisory (the "
    "model's output variables, not necessarily every decision variable). "
    "Enum-typed entries appear as `int`; enum names are not surfaced in v1."
)

FIND_UNSAT_CORE_DESCRIPTION = (
    "Diagnose an unsatisfiable MiniZinc model by computing a minimal "
    "unsatisfiable subset (MUS) of its constraints via the managed "
    "runtime's findMUS tool. Use it when solve_minizinc_model returns "
    "'unsatisfiable'. Optional `data` is `.dzn` text; pass the SAME `data` "
    "you solved with (omit it when the model needs none). Returns an "
    "UnsatCoreResult: `status` "
    "(`mus_found`/`no_core`/`error`/`timeout`), `core`, `message`, raw "
    "`stdout`/`stderr`, `elapsed_ms`. `core` is a best-effort structured "
    "list (source span + text) resolved from the MODEL FILE only — a "
    "decision variable assigned in `data` acts as a constraint, so a MUS "
    "member can originate in the data file and appear in authoritative "
    "`stdout` but not in `core`. The subset is MINIMAL, but not necessarily "
    "the globally smallest, and a model may have several."
)

SAVE_VERIFIED_MINIZINC_MODEL_DESCRIPTION = (
    "Save a successful inline MiniZinc workflow to a LOCAL project directory "
    "AFTER re-verifying it through the managed local runtime. The server "
    "trusts no prior claim of success: it re-runs the compile check and the "
    "solve on the supplied `model` (with the optional `data` and inline "
    "`checker`), and writes only when the check is `ok` and the solve is "
    "`satisfied`/`optimal` with a clean exit and no timeout — and, when a "
    "checker is supplied, the nested checker report is `completed` (the "
    "checker ran without machine-readable violation; that is NOT a proof of "
    "optimality). `target_dir` must be an EXPLICIT ABSOLUTE local directory "
    "path whose parent exists; the server never opens an OS file dialog or "
    "picker — the client asks the user for the path (or uses its own UI) and "
    "passes it here. The saved directory uses fixed filenames: `model.mzn`; "
    "`data.dzn`, `checker.mzc.mzn`, and `problem.md` only when `data`, "
    "`checker`, and `problem` (the user's original natural-language problem "
    "text, saved only when passed explicitly) are supplied; "
    "`solve-result.json` (the verifying SolveResult); and a "
    "`.openconstraint-model.json` manifest recording tool version, "
    "timestamp, solver, the solve controls used, a verification summary, and "
    "per-file sha256 hashes. Overwrite is MARKER-GATED: a new path or an "
    "empty directory is written directly; a non-empty directory is replaced "
    "— wholesale, via a staged sibling and atomic swap — only when it holds "
    "a prior save's manifest marker, `overwrite=true` is passed, and it "
    "contains no files the prior save did not write; anything else is "
    "refused with an actionable error and nothing is touched. Accepts the "
    "same `solver`, `timeout_ms`, and solver/search controls as "
    "`solve_minizinc_model` (`free_search`, `parallel`, `random_seed`, "
    "`all_solutions`, and the solver-gated `num_solutions`). Returns a "
    "SaveVerifiedModelResult: `status` (`saved`/`not_verified`), `message`, "
    "the resolved `target_dir`, `files` (role, bare filename, sha256 — "
    "populated only on `saved`), `check` (always present), and `solve` "
    "(null when the check gate already failed). A model that fails any "
    "verification gate returns `not_verified` with the gating results and "
    "writes NOTHING; argument/path problems are MCP errors. Runs entirely "
    "locally through the managed runtime: no network calls, no LLM "
    "invocation, no telemetry."
)

# Shared guidance injected into each path-based file-tool description.
_FILE_TOOL_SHARED_DESCRIPTION = (
    "Reads the model (and optional data) from local FILE PATHS on the "
    "machine running the server and runs the managed runtime from the "
    "model's own directory, so a relative `include` resolves just like a "
    "hand-run `minizinc`. `model_path` is a required `.mzn` path (must "
    "exist and be a regular file); `data_path` is an optional `.dzn` path. "
    "Paths resolve to absolute (prefer absolute); a missing/non-file, "
    "empty, or non-UTF-8 model is a clear MCP error before any run. It "
    "reads the model, the optional data, and any `include`d files; it never "
    "writes files, makes network calls, uploads data, or uses a remote "
    "solver."
)

CHECK_MINIZINC_FILES_DESCRIPTION = (
    "Compile-check a MiniZinc model from local file paths WITHOUT solving "
    "it — the path-based sibling of `check_minizinc_model`. "
    + _FILE_TOOL_SHARED_DESCRIPTION
    + " Returns the same CheckResult shape (`status` "
    "`ok`/`error`/`timeout`, `solver`, `stdout`, `stderr`, `elapsed_ms`); "
    "`ok` means it compiles, not that it is satisfiable."
)

SOLVE_MINIZINC_FILES_DESCRIPTION = (
    "Solve a MiniZinc model from local file paths — the path-based sibling "
    "of `solve_minizinc_model`. "
    + _FILE_TOOL_SHARED_DESCRIPTION
    + " Returns the same SolveResult shape (`status`, `solver`, "
    "`return_code`, `timed_out`, `elapsed_ms`, `stdout`, `stderr`, "
    "`solution`, `solutions`, `objective`, `statistics`, and `checker`) and the same "
    "model-visible `Statistics:` summary whenever the parsed map is "
    "non-empty, with an explicit final-answer requirement to copy the entire "
    "section rather than summarizing selected fields. Accepts the same "
    "optional solver/search controls as `solve_minizinc_model` "
    "(`free_search`, `parallel`, `random_seed`, `all_solutions`, and the "
    "solver-gated, satisfaction-only `num_solutions`). Optional `checker_path` "
    "points to a `.mzc`/`.mzc.mzn` checker file, resolved to absolute and "
    "validated before any run; it adds exactly `--solution-checker <path>` to the "
    "same solve invocation, so all search controls compose with checking. When "
    "supplied, `checker` in the SolveResult is the same nested CheckerReport "
    "described for `solve_minizinc_model`, including `status`, index-aligned "
    "`checks`, and authoritative raw `transcript`."
)

FIND_UNSAT_CORE_FILES_DESCRIPTION = (
    "Diagnose an unsatisfiable MiniZinc model from local file paths by "
    "computing a minimal unsatisfiable subset (MUS) via the managed "
    "runtime's findMUS tool — the path-based sibling of `find_unsat_core`. "
    + _FILE_TOOL_SHARED_DESCRIPTION
    + " Returns the same UnsatCoreResult shape (`status` "
    "`mus_found`/`no_core`/`error`/`timeout`, `core`, `message`, `stdout`, "
    "`stderr`, `elapsed_ms`). `core` resolves from the ENTRY MODEL FILE "
    "only, so a MUS member in an INCLUDED file appears in authoritative "
    "`stdout` but NOT in `core`. The subset is MINIMAL but not necessarily "
    "the globally smallest."
)

INSPECT_MINIZINC_FILES_DESCRIPTION = (
    "Inspect a MiniZinc model's INTERFACE from local file paths WITHOUT "
    "solving it — the path-based sibling of `inspect_minizinc_model`. "
    + _FILE_TOOL_SHARED_DESCRIPTION
    + " Returns the same ModelInspectionResult shape (`status` "
    "`ok`/`error`/`timeout`, `solver`, `stdout`, `stderr`, `elapsed_ms`, and "
    "the structured `interface` only when `ok`). `required_parameters` lists "
    "the parameters still needing a value given any `data_path`; an empty "
    '`required_parameters` means the data is complete, but `status="ok"` '
    "alone does NOT — it means only that the interface was extracted. Enum "
    "names are not surfaced in v1."
)

SUBMIT_SOLVE_JOB_DESCRIPTION = (
    "Submit a MiniZinc solve as a BACKGROUND JOB and return immediately, so a "
    "hard solve cannot hit a synchronous MCP client timeout. Takes the same "
    "inline surface as `solve_minizinc_model` — `model` (full source), optional "
    "`data`/`checker`, `solver`, `timeout_ms`, and the solver/search controls "
    "`free_search`, `parallel`, `random_seed`, `all_solutions`, and the "
    "solver-gated, satisfaction-only `num_solutions`. Argument errors (empty "
    "model, non-positive timeout, bad `parallel`/`num_solutions`) are reported "
    "synchronously as MCP errors before any job exists. Returns a SolveJobStatus "
    "with a server-generated opaque `job_id` and `state` `queued` or `running`; "
    "poll it with `get_solve_job(job_id)` and stop it with "
    "`cancel_solve_job(job_id)`. Admission is BOUNDED: at most a fixed number of "
    "jobs run at once, further submits sit `queued` up to a fixed cap, and a "
    "submit beyond that is REJECTED with an MCP error (retry once a running job "
    "finishes) rather than growing unboundedly. The registry is in-process and "
    "ephemeral — jobs do not survive a server restart, and finished jobs are "
    "retained only up to a cap (oldest evicted). This tool returns at once, so "
    "it emits no progress/log status milestones; watch `state` via "
    "`get_solve_job` instead. Runs entirely locally through the managed runtime: "
    "no network calls, no LLM invocation, no telemetry."
)

GET_SOLVE_JOB_DESCRIPTION = (
    "Poll a background solve job by its `job_id` (from `submit_solve_job`). "
    "Returns a SolveJobStatus: `job_id`, `state`, `solver`, `timeout_ms`, "
    "`submitted_at_ms`, `started_at_ms`, `finished_at_ms`, `elapsed_ms`, an "
    "optional `result` (the full SolveResult), and an optional `message`. "
    "`state` is one of `queued`, "
    "`running`, `succeeded`, `failed`, `timeout`, `cancelled`. CONTRACT: "
    "`result` is present exactly when `state` is `succeeded` or `timeout`, and "
    "absent for `queued`/`running`/`failed`/`cancelled`. So `failed` implies "
    "`result is None`, but NOT the converse — `queued`/`running`/`cancelled` carry "
    "no result either, so branch on `state`, not on `result`. `failed` means the "
    "job machinery itself "
    "raised (no SolveResult, see `message`); a SOLVER-level `error` verdict is a "
    "`succeeded` job whose `result.status == \"error\"`, NOT `failed`. A `timeout` "
    "job still carries its partial SolveResult. While a job is `running` only "
    "`state` + `elapsed_ms` advance; live mid-solve statistics are not provided. "
    "PACE your polling against the job's own budget rather than a fixed `sleep`: "
    "`timeout_ms` is the requested solve time-limit and `elapsed_ms` how long the "
    "job has run, so a `running` job has roughly `timeout_ms - elapsed_ms` left "
    "and is usually terminal shortly after that — wait a fraction of the "
    "remaining budget between polls instead of looping tightly or guessing an "
    "interval, since a `running` job exposes no new data between polls. "
    "On a `succeeded` or `timeout` job, present `result` the way the synchronous "
    "solve tools require: lead with the plain-language status and the solution in "
    "the user's terms, and include the COMPLETE model-visible `Statistics:` "
    "section whenever `result.statistics` is non-empty — do not omit, summarize, "
    "or condense it to selected fields. An unknown `job_id` is an MCP error."
)

CANCEL_SOLVE_JOB_DESCRIPTION = (
    "Request cancellation of a background solve job by `job_id`. A job still "
    "`queued` is dropped before it starts; a `running` job has its managed "
    "MiniZinc process tree (the solver children too) terminated. Cancellation "
    "is best-effort and idempotent: cancelling an already-terminal job "
    "(`succeeded`/`failed`/`timeout`/`cancelled`) is a no-op that returns the "
    "current status unchanged. Returns the SolveJobStatus; the job reaches "
    "`cancelled` (with `result is None`) once the worker observes the request — "
    "poll `get_solve_job` to confirm the terminal state. An unknown `job_id` is "
    "an MCP error."
)

LIST_SOLVE_JOBS_DESCRIPTION = (
    "List the currently retained background solve jobs as SolveJobStatus "
    "entries (one per job), covering every state from `queued` to terminal. The "
    "registry is in-process and bounded: finished jobs are retained only up to a "
    "cap, so the oldest terminal jobs may have been evicted and a restart clears "
    "all of them. Takes no arguments and never downloads or runs anything."
)

SOLVE_CONSTRAINT_PROBLEM_PROMPT_DESCRIPTION = (
    "Guide the MCP client's LLM through translating a natural-language "
    "constraint or optimization problem into MiniZinc and running it "
    "through the local managed runtime (via solve_minizinc_model when "
    "available, otherwise by walking the user through the "
    "openconstraint-mcp CLI to set up and invoke the managed runtime "
    "manually — never via a bare PATH-based minizinc)."
)
